[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.1"
  export = ["byoc_98_test"]
  icon = "docs/icon.png"
  keywords = ["Type/RestApi","Category/Service","Internal/http"]
  name = "byoc_98_test"
  org = "yashodperera"
  version = "1.1.0"

