[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.2.3"
  export = ["greeting_service_kq"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "greeting_service_kq"
  org = "choreouptime"
  version = "1.2.1"

