[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.2.3"
  export = ["echo_service"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "echo_service"
  org = "yashodperera"
  version = "1.2.1"

